[project]
name = "blockchain-pharmaceutical-supply-chain"
description = "Blockchain project: blockchain-pharmaceutical-supply-chain"
authors = ["Automated Builder <automation@blockchain.dev>"]
telemetry = false
cache_dir = ".clarinet"
requirements = []

[contracts.regulatory-compliance-monitor]
path = "contracts/regulatory-compliance-monitor.clar"
depends_on = []

[contracts.drug-authenticity-tracker]
path = "contracts/drug-authenticity-tracker.clar"
depends_on = []

